### ISSUE TITLE
Messages Self Deleting 

### ISSUE THREAD

**Issue by amuro11** [johan-sorman/Where-Is-DI-Discord-Bot-Report-Issues#1]
Hello good morning/afternoon, I'm reaching out in regards to the Di bot you had created. Users in my discord have been contacting me that the messages the bot leaves get deleted almost instantly, even with the appropriate commands and name of the channel. The bot was working fine up until last night. Would appreciate any help on the matter, thanks you.

**Comment by johan-sorman** [comment]
Hi @amuro11, 

Could you provide me more information about the channel name and if possible, screenshots when this happens? 

I'm unable to replicate this error on my test server or another server that has the bot, which leads me to believe it might be a user error.

**Comment by amuro11** [comment]
yes the channel name is where-is-di
![Feedback](https://user-images.githubusercontent.com/122807378/212770915-298eb57e-1bb5-4c34-a08b-02b865be2808.png)

**Comment by amuro11** [comment]
this only started to happen early this morning, from Saturday evening until early this morning it was working as intended.

**Comment by johan-sorman** [comment]
Very odd. It looks correct from your screenshot. I have pushed an update and the bot should be rebooted in the next couple of minutes. If the issue still persists, try kicking the bot and re-invite it.
