### ISSUE TITLE
Is the DI bot offline for maintenance?

### ISSUE THREAD

**Issue by rhwymer** [johan-sorman/Where-Is-DI-Discord-Bot-Report-Issues#2]
I am very thankful for this Where-Is-DI-Bot!
It is one of the most used bots on my Linkshell's discord server.
However, it is offline at the moment. 
Are there plans to bring it back,? Or is there another way I can pass the information into discord?
Thanks!

**Comment by johan-sorman** [comment]
Sorry for the late reply. I had an internet outage so it was down temporarily.
